// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MosaicMoney.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MosaicMoney.Api.Migrations
{
    [DbContext(typeof(MosaicMoneyDbContext))]
    [Migration("20260222225205_MmBe07A08ARecurringAndReimbursementContracts")]
    partial class MmBe07A08ARecurringAndReimbursementContracts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "azure_ai");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalAccountKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "ExternalAccountKey")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.ClassificationStageOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<bool>("EscalatedToNextStage")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OutcomeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProducedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProposedSubcategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RationaleCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProposedSubcategoryId");

                    b.HasIndex("OutcomeId", "Stage")
                        .IsUnique();

                    b.ToTable("ClassificationStageOutputs", t =>
                        {
                            t.HasCheckConstraint("CK_ClassificationStageOutput_ConfidenceRange", "\"Confidence\" >= 0 AND \"Confidence\" <= 1");

                            t.HasCheckConstraint("CK_ClassificationStageOutput_StageOrderRange", "\"StageOrder\" >= 1 AND \"StageOrder\" <= 3");
                        });
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentNote")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Vector>("DescriptionEmbedding")
                        .HasColumnType("vector(1536)");

                    b.Property<bool>("ExcludeFromBudget")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExtraPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NeedsReviewByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlaidTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("RecurringItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DescriptionEmbedding")
                        .HasFilter("\"DescriptionEmbedding\" IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DescriptionEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DescriptionEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("NeedsReviewByUserId");

                    b.HasIndex("PlaidTransactionId")
                        .IsUnique();

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("RecurringItemId", "TransactionDate");

                    b.HasIndex("ReviewStatus", "NeedsReviewByUserId", "TransactionDate");

                    b.ToTable("EnrichedTransactions");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.HouseholdUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalUserKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "ExternalUserKey")
                        .IsUnique();

                    b.ToTable("HouseholdUsers");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.RawTransactionIngestionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeltaCursor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("EnrichedTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastDisposition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastReviewReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceTransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("EnrichedTransactionId");

                    b.HasIndex("Source", "SourceTransactionId", "LastProcessedAtUtc");

                    b.HasIndex("Source", "DeltaCursor", "SourceTransactionId", "PayloadHash")
                        .IsUnique();

                    b.ToTable("RawTransactionIngestionRecords");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.RecurringItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentNote")
                        .HasColumnType("text");

                    b.Property<decimal>("AmountScoreWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("AmountVarianceAbsolute")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountVariancePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DeterministicMatchThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("DeterministicScoreVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("DueDateScoreWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("DueWindowDaysAfter")
                        .HasColumnType("integer");

                    b.Property<int>("DueWindowDaysBefore")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVariable")
                        .HasColumnType("boolean");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("NextDueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("RecencyScoreWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("TieBreakPolicy")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("RecurringItems", t =>
                        {
                            t.HasCheckConstraint("CK_RecurringItem_DeterministicMetadataRequired", "LENGTH(TRIM(\"DeterministicScoreVersion\")) > 0 AND LENGTH(TRIM(\"TieBreakPolicy\")) > 0");

                            t.HasCheckConstraint("CK_RecurringItem_DeterministicThresholdRange", "\"DeterministicMatchThreshold\" >= 0 AND \"DeterministicMatchThreshold\" <= 1");

                            t.HasCheckConstraint("CK_RecurringItem_DueWindowRange", "\"DueWindowDaysBefore\" >= 0 AND \"DueWindowDaysBefore\" <= 90 AND \"DueWindowDaysAfter\" >= 0 AND \"DueWindowDaysAfter\" <= 90");

                            t.HasCheckConstraint("CK_RecurringItem_ScoreWeightsRange", "\"DueDateScoreWeight\" >= 0 AND \"DueDateScoreWeight\" <= 1 AND \"AmountScoreWeight\" >= 0 AND \"AmountScoreWeight\" <= 1 AND \"RecencyScoreWeight\" >= 0 AND \"RecencyScoreWeight\" <= 1");

                            t.HasCheckConstraint("CK_RecurringItem_ScoreWeightsSum", "ROUND(\"DueDateScoreWeight\" + \"AmountScoreWeight\" + \"RecencyScoreWeight\", 4) = 1");

                            t.HasCheckConstraint("CK_RecurringItem_VarianceRange", "\"AmountVariancePercent\" >= 0 AND \"AmountVariancePercent\" <= 100 AND \"AmountVarianceAbsolute\" >= 0");
                        });
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.ReimbursementProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecisionedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecisionedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IncomingTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LifecycleGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("LifecycleOrdinal")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalSource")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProposedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProvenancePayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("ProvenanceReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProvenanceSource")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTransactionSplitId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusRationale")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StatusReasonCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("SupersedesProposalId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DecisionedByUserId");

                    b.HasIndex("RelatedTransactionId");

                    b.HasIndex("RelatedTransactionSplitId");

                    b.HasIndex("SupersedesProposalId");

                    b.HasIndex("IncomingTransactionId", "Status");

                    b.HasIndex("LifecycleGroupId", "CreatedAtUtc");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.HasIndex("IncomingTransactionId", "LifecycleGroupId", "LifecycleOrdinal")
                        .IsUnique();

                    b.ToTable("ReimbursementProposals", t =>
                        {
                            t.HasCheckConstraint("CK_ReimbursementProposal_DecisionAuditForFinalStates", "(\"Status\" IN (2, 3) AND \"DecisionedByUserId\" IS NOT NULL AND \"DecisionedAtUtc\" IS NOT NULL) OR (\"Status\" NOT IN (2, 3))");

                            t.HasCheckConstraint("CK_ReimbursementProposal_LifecycleOrdinal", "\"LifecycleOrdinal\" >= 1");

                            t.HasCheckConstraint("CK_ReimbursementProposal_OneRelatedTarget", "(\"RelatedTransactionId\" IS NOT NULL AND \"RelatedTransactionSplitId\" IS NULL) OR (\"RelatedTransactionId\" IS NULL AND \"RelatedTransactionSplitId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ReimbursementProposal_ProvenanceRequired", "LENGTH(TRIM(\"ProvenanceSource\")) > 0");

                            t.HasCheckConstraint("CK_ReimbursementProposal_RationaleRequired", "LENGTH(TRIM(\"StatusReasonCode\")) > 0 AND LENGTH(TRIM(\"StatusRationale\")) > 0");
                        });
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBusinessExpense")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.TransactionClassificationOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentNoteSummary")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<string>("DecisionRationale")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DecisionReasonCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("FinalConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid?>("ProposedSubcategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProposedSubcategoryId");

                    b.HasIndex("TransactionId", "CreatedAtUtc");

                    b.HasIndex("Decision", "ReviewStatus", "CreatedAtUtc");

                    b.ToTable("TransactionClassificationOutcomes", t =>
                        {
                            t.HasCheckConstraint("CK_TransactionClassificationOutcome_DecisionReviewRouting", "(\"Decision\" = 2 AND \"ReviewStatus\" = 1) OR (\"Decision\" = 1 AND \"ReviewStatus\" <> 1)");

                            t.HasCheckConstraint("CK_TransactionClassificationOutcome_FinalConfidenceRange", "\"FinalConfidence\" >= 0 AND \"FinalConfidence\" <= 1");
                        });
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.TransactionSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentNote")
                        .HasColumnType("text");

                    b.Property<int>("AmortizationMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ParentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentTransactionId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("TransactionSplits");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Account", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Household", "Household")
                        .WithMany("Accounts")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.ClassificationStageOutput", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.TransactionClassificationOutcome", "Outcome")
                        .WithMany("StageOutputs")
                        .HasForeignKey("OutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Subcategory", "ProposedSubcategory")
                        .WithMany("ClassificationStageProposals")
                        .HasForeignKey("ProposedSubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Outcome");

                    b.Navigation("ProposedSubcategory");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.HouseholdUser", "NeedsReviewByUser")
                        .WithMany("NeedsReviewTransactions")
                        .HasForeignKey("NeedsReviewByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.RecurringItem", "RecurringItem")
                        .WithMany("Transactions")
                        .HasForeignKey("RecurringItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Subcategory", "Subcategory")
                        .WithMany("Transactions")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("NeedsReviewByUser");

                    b.Navigation("RecurringItem");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.HouseholdUser", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.RawTransactionIngestionRecord", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", "EnrichedTransaction")
                        .WithMany("RawIngestionRecords")
                        .HasForeignKey("EnrichedTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("EnrichedTransaction");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.RecurringItem", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Household", "Household")
                        .WithMany("RecurringItems")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.ReimbursementProposal", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.HouseholdUser", null)
                        .WithMany()
                        .HasForeignKey("DecisionedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", "IncomingTransaction")
                        .WithMany("ReimbursementProposals")
                        .HasForeignKey("IncomingTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", null)
                        .WithMany()
                        .HasForeignKey("RelatedTransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.TransactionSplit", null)
                        .WithMany()
                        .HasForeignKey("RelatedTransactionSplitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.ReimbursementProposal", "SupersedesProposal")
                        .WithMany("SupersededByProposals")
                        .HasForeignKey("SupersedesProposalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IncomingTransaction");

                    b.Navigation("SupersedesProposal");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Subcategory", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.TransactionClassificationOutcome", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Subcategory", "ProposedSubcategory")
                        .WithMany("ClassificationOutcomeProposals")
                        .HasForeignKey("ProposedSubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", "Transaction")
                        .WithMany("ClassificationOutcomes")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedSubcategory");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.TransactionSplit", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", "ParentTransaction")
                        .WithMany("Splits")
                        .HasForeignKey("ParentTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Subcategory", "Subcategory")
                        .WithMany("Splits")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentTransaction");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", b =>
                {
                    b.Navigation("ClassificationOutcomes");

                    b.Navigation("RawIngestionRecords");

                    b.Navigation("ReimbursementProposals");

                    b.Navigation("Splits");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Household", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RecurringItems");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.HouseholdUser", b =>
                {
                    b.Navigation("NeedsReviewTransactions");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.RecurringItem", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.ReimbursementProposal", b =>
                {
                    b.Navigation("SupersededByProposals");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Subcategory", b =>
                {
                    b.Navigation("ClassificationOutcomeProposals");

                    b.Navigation("ClassificationStageProposals");

                    b.Navigation("Splits");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.TransactionClassificationOutcome", b =>
                {
                    b.Navigation("StageOutputs");
                });
#pragma warning restore 612, 618
        }
    }
}
