// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MosaicMoney.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MosaicMoney.Api.Migrations
{
    [DbContext(typeof(MosaicMoneyDbContext))]
    [Migration("20260222215807_MmBe03Be04InitialContract")]
    partial class MmBe03Be04InitialContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "azure_ai");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalAccountKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "ExternalAccountKey")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentNote")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Vector>("DescriptionEmbedding")
                        .HasColumnType("vector(1536)");

                    b.Property<bool>("ExcludeFromBudget")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExtraPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NeedsReviewByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlaidTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("RecurringItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DescriptionEmbedding")
                        .HasFilter("\"DescriptionEmbedding\" IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DescriptionEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DescriptionEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("NeedsReviewByUserId");

                    b.HasIndex("PlaidTransactionId")
                        .IsUnique();

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("RecurringItemId", "TransactionDate");

                    b.HasIndex("ReviewStatus", "NeedsReviewByUserId", "TransactionDate");

                    b.ToTable("EnrichedTransactions");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.HouseholdUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalUserKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "ExternalUserKey")
                        .IsUnique();

                    b.ToTable("HouseholdUsers");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.RecurringItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentNote")
                        .HasColumnType("text");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVariable")
                        .HasColumnType("boolean");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("NextDueDate")
                        .HasColumnType("date");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("RecurringItems");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.ReimbursementProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecisionedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecisionedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IncomingTransactionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ProposedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTransactionSplitId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DecisionedByUserId");

                    b.HasIndex("RelatedTransactionId");

                    b.HasIndex("RelatedTransactionSplitId");

                    b.HasIndex("IncomingTransactionId", "Status");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("ReimbursementProposals", t =>
                        {
                            t.HasCheckConstraint("CK_ReimbursementProposal_OneRelatedTarget", "(\"RelatedTransactionId\" IS NOT NULL AND \"RelatedTransactionSplitId\" IS NULL) OR (\"RelatedTransactionId\" IS NULL AND \"RelatedTransactionSplitId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBusinessExpense")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.TransactionSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentNote")
                        .HasColumnType("text");

                    b.Property<int>("AmortizationMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ParentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentTransactionId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("TransactionSplits");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Account", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Household", "Household")
                        .WithMany("Accounts")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.HouseholdUser", "NeedsReviewByUser")
                        .WithMany("NeedsReviewTransactions")
                        .HasForeignKey("NeedsReviewByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.RecurringItem", "RecurringItem")
                        .WithMany("Transactions")
                        .HasForeignKey("RecurringItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Subcategory", "Subcategory")
                        .WithMany("Transactions")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("NeedsReviewByUser");

                    b.Navigation("RecurringItem");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.HouseholdUser", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.RecurringItem", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Household", "Household")
                        .WithMany("RecurringItems")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.ReimbursementProposal", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.HouseholdUser", null)
                        .WithMany()
                        .HasForeignKey("DecisionedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", null)
                        .WithMany()
                        .HasForeignKey("IncomingTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", null)
                        .WithMany()
                        .HasForeignKey("RelatedTransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.TransactionSplit", null)
                        .WithMany()
                        .HasForeignKey("RelatedTransactionSplitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Subcategory", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.TransactionSplit", b =>
                {
                    b.HasOne("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", "ParentTransaction")
                        .WithMany("Splits")
                        .HasForeignKey("ParentTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosaicMoney.Api.Domain.Ledger.Subcategory", "Subcategory")
                        .WithMany("Splits")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentTransaction");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.EnrichedTransaction", b =>
                {
                    b.Navigation("Splits");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Household", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RecurringItems");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.HouseholdUser", b =>
                {
                    b.Navigation("NeedsReviewTransactions");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.RecurringItem", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MosaicMoney.Api.Domain.Ledger.Subcategory", b =>
                {
                    b.Navigation("Splits");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
